### ISSUE TITLE
Chose appropriate license

### ISSUE THREAD

**Issue by tingerrr** [typst-community/guidelines#10]
A suggestion by @PgBiel was `CC-BY 4.0`.

**Comment by ensko** [comment]
is there a specific reason for CC BY over CC BY-SA? At least superficially, it seems similar to MIT vs GPL (enforcing the same license on downstream adaptors). With documentation style content, the SA restriction seems fairly harmless compared to copyleft on code.

Basically: is allowing/preventing the guidelines being remixed into non-CC works a bug or a feature?

**Comment by PgBiel** [comment]
My suggestion (over Discord) was just what felt to be the most harmless option. I don't really mind going with either license.

**Comment by tingerrr** [comment]
Since this is not a package or library of any kind, I think it's fine to require derivatives of the work to be shared under the same terms. Ideally, if someone feels like forking and fixing all my typos, the community should benefit from the improved work.

That is, if I understood the SA clause correctly. The wording implies that derivatives _must be shared_, but I'm not sure if this implies must be shared _with the public_.

**Comment by PgBiel** [comment]
Sure

**Comment by ensko** [comment]
Good for me too!
