### ISSUE TITLE
Guidelines not respected in code

### ISSUE THREAD

**Issue by Ciflire** [typst-community/guidelines#3]
So I might not understand what you mean in `Traling Content Argument` but you say that if there are multiple arguments they should be inside function call but for your `do-dont` (cf `flexibility.typ`L35) you're not using this guideline in your code
It might be hard to debug after but if it's a more natural way to do it maybe it should be standard ?
Also i see you're the only contributor to this repo, i just want to know if other people participated at giving their opinion or not?

**Comment by tingerrr** [comment]
The section on trailing content args is perhaps a little incorrect, I think in general it's fine to use it for short runs of args or where it's easy to read. Whereas for tables (the example use in that section) it's more often relevant where you usually have multiple rows of args which are harder to spot and refactor with the trailing syntax.

Perhaps it should be rephrased to state this in a more obvious manner.

> Also i see you're the only contributor to this repo, i just want to know if other people participated at giving their opinion or not?

I collect most of the info from the community discord, packages source code and my own experience on using and working on packages.
